'use strict';

const { PDFDocument, rgb, StandardFonts } = PDFLib;

function safeText(id,v){const e=document.getElementById(id);if(e)e.textContent=String(v);}
function getEl(id){return document.getElementById(id);}
function sanitizeStr(s,max){return String(s).replace(/[<>]/g,'').substring(0,max);}

// ── Tabs ──────────────────────────────────────────────────────────────────────
document.querySelectorAll('.tool-tab').forEach(tab=>{
  tab.addEventListener('click',()=>{
    document.querySelectorAll('.tool-tab').forEach(t=>{t.classList.remove('active');t.setAttribute('aria-selected','false');});
    document.querySelectorAll('.tool-panel').forEach(p=>p.style.display='none');
    tab.classList.add('active'); tab.setAttribute('aria-selected','true');
    const panel=getEl('panel-'+tab.dataset.tool);
    if(panel)panel.style.display='block';
    getEl('pdf-status').style.display='none';
  });
});

// ── Status ────────────────────────────────────────────────────────────────────
function showStatus(msg,type='info'){
  const el=getEl('pdf-status');
  el.textContent=msg; el.style.display='block';
  el.className='pdf-status pdf-status-'+type;
}

// ── Text to PDF ───────────────────────────────────────────────────────────────
getEl('pdfContent').addEventListener('input',function(){
  const count=this.value.length;
  safeText('charCount', count.toLocaleString()+' / 50,000 characters');
});

async function generatePDF(){
  const rawTitle   = sanitizeStr(getEl('pdfTitle').value   || 'My Document', 100);
  const rawAuthor  = sanitizeStr(getEl('pdfAuthor').value  || '', 80);
  const rawContent = sanitizeStr(getEl('pdfContent').value || '', 50000);

  if(!rawContent.trim()) return showStatus('⚠️ Please enter some text content.','error');

  try {
    showStatus('⏳ Generating your PDF…','info');
    const pdfDoc = await PDFDocument.create();
    pdfDoc.setTitle(rawTitle);
    if(rawAuthor) pdfDoc.setAuthor(rawAuthor);
    pdfDoc.setCreationDate(new Date());

    const font      = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont  = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const pageW=595, pageH=842, margin=60, lineH=18, fontSize=11;
    const maxW = pageW - margin*2;

    const wrapText=(text,f,size,maxWidth)=>{
      const words=text.split(' ');const lines=[];let cur='';
      words.forEach(w=>{
        const test=cur?cur+' '+w:w;
        if(f.widthOfTextAtSize(test,size)>maxWidth&&cur){lines.push(cur);cur=w;}
        else cur=test;
      });
      if(cur)lines.push(cur);
      return lines;
    };

    let page=pdfDoc.addPage([pageW,pageH]);
    let y=pageH-margin;

    // Title
    const titleLines=wrapText(rawTitle,boldFont,16,maxW);
    titleLines.forEach(l=>{
      if(y<margin){page=pdfDoc.addPage([pageW,pageH]);y=pageH-margin;}
      page.drawText(l,{x:margin,y,font:boldFont,size:16,color:rgb(0.18,0.14,0.09)});
      y-=24;
    });
    if(rawAuthor){
      page.drawText('By '+rawAuthor,{x:margin,y,font,size:10,color:rgb(0.6,0.5,0.4)});
      y-=16;
    }
    y-=10;
    page.drawLine({start:{x:margin,y},end:{x:pageW-margin,y},thickness:0.5,color:rgb(0.8,0.75,0.65)});
    y-=18;

    // Body
    const paragraphs=rawContent.split('\n');
    paragraphs.forEach(para=>{
      if(!para.trim()){y-=lineH/2;return;}
      const lines=wrapText(para,font,fontSize,maxW);
      lines.forEach(l=>{
        if(y<margin){page=pdfDoc.addPage([pageW,pageH]);y=pageH-margin;}
        page.drawText(l,{x:margin,y,font,size:fontSize,color:rgb(0.18,0.14,0.09)});
        y-=lineH;
      });
      y-=lineH/2;
    });

    // Footer on each page
    const pages=pdfDoc.getPages();
    pages.forEach((p,i)=>{
      p.drawText(`Page ${i+1} of ${pages.length}  ·  Generated by ToolSuite`,
        {x:margin,y:30,font,size:8,color:rgb(0.7,0.65,0.55)});
    });

    const bytes=await pdfDoc.save();
    download(bytes,'document.pdf','application/pdf');
    showStatus('✅ PDF downloaded successfully!','success');
  } catch(e){ showStatus('❌ Error generating PDF. Please try again.','error'); }
}

// ── Merge PDFs ────────────────────────────────────────────────────────────────
let mergeFiles=[];

function setupMergeDrop(){
  const drop=getEl('merge-drop'), input=getEl('merge-input');
  drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag-over');});
  drop.addEventListener('dragleave',()=>drop.classList.remove('drag-over'));
  drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag-over');addMergeFiles(e.dataTransfer.files);});
  input.addEventListener('change',()=>addMergeFiles(input.files));
}

function addMergeFiles(files){
  Array.from(files).forEach(f=>{
    if(f.type==='application/pdf'&&f.size<50*1024*1024) mergeFiles.push(f);
  });
  renderMergeList();
}

function renderMergeList(){
  const list=getEl('merge-file-list'); list.innerHTML='';
  mergeFiles.forEach((f,i)=>{
    const item=document.createElement('div'); item.className='file-item';
    const nameEl=document.createElement('span'); nameEl.className='file-name';
    nameEl.textContent=f.name.substring(0,50)+(f.size?(' — '+(f.size/1024).toFixed(0)+' KB'):'');
    const rm=document.createElement('button'); rm.className='file-remove'; rm.type='button'; rm.textContent='✕';
    rm.addEventListener('click',()=>{mergeFiles.splice(i,1);renderMergeList();});
    item.appendChild(nameEl); item.appendChild(rm); list.appendChild(item);
  });
}

async function mergePDFs(){
  if(mergeFiles.length<2) return showStatus('⚠️ Please select at least 2 PDF files.','error');
  try{
    showStatus('⏳ Merging your PDFs…','info');
    const merged=await PDFDocument.create();
    for(const f of mergeFiles){
      const buf=await f.arrayBuffer();
      const src=await PDFDocument.load(buf);
      const pages=await merged.copyPages(src,src.getPageIndices());
      pages.forEach(p=>merged.addPage(p));
    }
    const bytes=await merged.save();
    download(bytes,'merged.pdf','application/pdf');
    showStatus(`✅ ${mergeFiles.length} PDFs merged and downloaded!`,'success');
  }catch(e){showStatus('❌ Could not merge PDFs. Make sure all files are valid PDFs.','error');}
}

// ── Split PDF ─────────────────────────────────────────────────────────────────
let splitFile=null;

function setupSplitDrop(){
  const drop=getEl('split-drop'), input=getEl('split-input');
  drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag-over');});
  drop.addEventListener('dragleave',()=>drop.classList.remove('drag-over'));
  drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag-over');setSplitFile(e.dataTransfer.files[0]);});
  input.addEventListener('change',()=>setSplitFile(input.files[0]));
}

function setSplitFile(f){
  if(!f||f.type!=='application/pdf') return showStatus('⚠️ Please select a valid PDF file.','error');
  splitFile=f;
  const info=getEl('split-info'), fn=getEl('split-filename');
  if(fn) fn.textContent='📄 '+f.name+' ('+(f.size/1024).toFixed(0)+' KB)';
  if(info) info.style.display='block';
}

function parsePageRanges(str, maxPage){
  const pages=new Set();
  str.split(',').forEach(part=>{
    part=part.trim();
    if(part.includes('-')){
      const [a,b]=part.split('-').map(Number);
      if(!isNaN(a)&&!isNaN(b)&&a>=1&&b<=maxPage&&a<=b){
        for(let i=a;i<=b;i++) pages.add(i-1);
      }
    } else {
      const n=Number(part);
      if(!isNaN(n)&&n>=1&&n<=maxPage) pages.add(n-1);
    }
  });
  return [...pages].sort((a,b)=>a-b);
}

async function splitPDF(){
  if(!splitFile) return showStatus('⚠️ Please select a PDF file first.','error');
  const rangeStr=sanitizeStr(getEl('splitPages').value,'',100);
  if(!rangeStr.trim()) return showStatus('⚠️ Please enter page numbers to extract.','error');
  try{
    showStatus('⏳ Extracting pages…','info');
    const buf=await splitFile.arrayBuffer();
    const src=await PDFDocument.load(buf);
    const total=src.getPageCount();
    const indices=parsePageRanges(rangeStr,total);
    if(indices.length===0) return showStatus(`⚠️ No valid pages found. This PDF has ${total} pages.`,'error');
    const out=await PDFDocument.create();
    const copied=await out.copyPages(src,indices);
    copied.forEach(p=>out.addPage(p));
    const bytes=await out.save();
    download(bytes,'extracted-pages.pdf','application/pdf');
    showStatus(`✅ ${indices.length} page(s) extracted and downloaded!`,'success');
  }catch(e){showStatus('❌ Could not process PDF. Make sure the file is a valid PDF.','error');}
}

// ── Download helper ───────────────────────────────────────────────────────────
function download(bytes,filename,mime){
  const blob=new Blob([bytes],{type:mime});
  const url=URL.createObjectURL(blob);
  const a=document.createElement('a');
  a.href=url; a.download=filename; a.style.display='none';
  document.body.appendChild(a); a.click();
  setTimeout(()=>{URL.revokeObjectURL(url);a.remove();},2000);
}

// ── Extra styles ──────────────────────────────────────────────────────────────
const st=document.createElement('style');
st.textContent=`
.tool-tabs{display:flex;gap:8px;margin-bottom:24px;flex-wrap:wrap;}
.tool-tab{background:var(--surface2);border:1.5px solid var(--border);border-radius:var(--radius-sm);padding:10px 16px;font-family:var(--font-main);font-size:13px;font-weight:800;color:var(--text-mid);cursor:pointer;transition:all .2s;}
.tool-tab:hover{border-color:var(--gold);color:var(--gold-dark);}
.tool-tab.active{background:linear-gradient(135deg,#f5a623,#ff7c44);color:white;border-color:transparent;}
textarea{width:100%;background:var(--surface2);border:1.5px solid var(--border);border-radius:var(--radius-sm);padding:14px;font-family:var(--font-main);font-size:14px;color:var(--text);resize:vertical;outline:none;transition:border-color .2s;}
textarea:focus{border-color:var(--gold);box-shadow:0 0 0 3px rgba(245,166,35,.15);}
.drop-zone{border:2px dashed var(--border-hi);border-radius:var(--radius-sm);padding:40px 20px;text-align:center;cursor:pointer;transition:all .2s;background:var(--surface2);}
.drop-zone.drag-over{border-color:var(--gold);background:var(--gold-light);}
.drop-icon{font-size:40px;margin-bottom:12px;}
.drop-zone p{font-size:14px;color:var(--text-mid);margin-bottom:10px;}
.file-label{display:inline-block;background:linear-gradient(135deg,#f5a623,#ff7c44);color:white;padding:8px 20px;border-radius:999px;font-weight:800;font-size:13px;cursor:pointer;transition:all .2s;}
.file-label:hover{transform:translateY(-2px);box-shadow:var(--shadow-btn);}
.file-list{margin-top:14px;display:flex;flex-direction:column;gap:8px;}
.file-item{display:flex;align-items:center;justify-content:space-between;background:var(--surface2);border:1.5px solid var(--border);border-radius:var(--radius-xs);padding:10px 14px;}
.file-name{font-size:13px;font-weight:700;color:var(--text-mid);word-break:break-all;}
.file-remove{background:var(--red-light);border:1.5px solid #f5bfba;color:var(--red);border-radius:6px;width:28px;height:28px;cursor:pointer;font-size:12px;flex-shrink:0;margin-left:10px;}
.file-remove:hover{background:var(--red);color:white;}
.split-info{background:var(--gold-light);border:1.5px solid #f5d78e;border-radius:var(--radius-xs);padding:10px 14px;font-size:13px;font-weight:700;color:var(--gold-dark);margin-top:12px;}
.pdf-status{padding:14px 18px;border-radius:var(--radius-sm);font-size:14px;font-weight:700;margin-top:20px;transition:all .3s;}
.pdf-status-info{background:var(--blue-light);border:1.5px solid #a8d4f5;color:var(--blue);}
.pdf-status-success{background:var(--green-light);border:1.5px solid #a8e6c2;color:var(--green);}
.pdf-status-error{background:var(--red-light);border:1.5px solid #f5bfba;color:var(--red);}
`;
document.head.appendChild(st);

document.addEventListener('DOMContentLoaded',()=>{
  setupMergeDrop();
  setupSplitDrop();
});
